Repository safient/client, pull requests merged in 2022-01, with the labels that each got.

#93 #82 - Add a background overlay to loader component.
  package-lock.json
  src/assets/icons/lockLoader.gif
  src/components/primitive/generic-modal/generic-modal.component.style.ts
  src/components/primitive/generic-modal/generic-modal.component.tsx
  src/components/primitive/index.ts
  src/components/primitive/loader/loader.component.props.ts
  src/components/primitive/loader/loader.component.tsx
  src/components/primitive/notice-loader/notice-loader.component.props.ts
  src/components/primitive/notice-loader/notice-loader.component.styles.ts
  src/components/primitive/notice-loader/notice-loader.component.tsx
  src/i18n/locales/en.json
  src/screens/auth/login/login.screen.tsx
  src/themes/images.ts
Labels: enhancement

#94 #84 - Fix the overflow issues and change the border color of chip-Input component.
  src/components/primitive/chip-input/chip-input.component.props.ts
  src/components/primitive/chip-input/chip-input.component.styles.ts
  src/components/primitive/chip-input/chip-input.component.tsx
Labels: bug, enhancement

#73 #48 - Auth service layer integration with login screen
  package-lock.json
  package.json
  public/favicon.ico
  public/index.html
  public/manifest.json
  src/App.tsx
  src/assets/icons/notification.svg
  src/assets/icons/user.svg
  src/assets/index.ts
  src/components/primitive/top-bar/top-bar.component.tsx
  src/i18n/locales/en.json
  src/navigation/navigation.tsx
  src/navigation/routes.ts
  src/screens/account/account.screen.styles.ts
  src/screens/account/account.screen.tsx
  src/screens/auth/login/login.screen.tsx
  src/services/account/account.service.impl.ts
  src/services/account/account.service.ts
  src/services/core/service-response..ts
  src/services/core/service.ts
  src/services/core/services.ts
  src/services/ethereum/ethereum.service.impl.ts
  src/services/ethereum/ethereum.service.ts
  src/store/account/account.store.impl.ts
  src/store/account/account.store.ts
  src/themes/images.ts
  yarn.lock
Labels: feature

#91 #47 - Create a file uploader component
  src/components/primitive/file-uploader/file-uploader.component.props.ts
  src/components/primitive/file-uploader/file-uploader.component.tsx
Labels: enhancement

#113 #100 - Create guardians component
  src/i18n/locales/en.json
  src/navigation/navigation.tsx
  src/navigation/route-name.ts
  src/navigation/route-path.ts
  src/navigation/routes.ts
  src/screens/index.ts
  src/screens/safe-overview/containers/guardians.component.tsx
  src/screens/safe-overview/safe-overview.screen.tsx
Labels: feature

#114 #98 - Rename badge component to label
  src/components/primitive/index.ts
  src/components/primitive/label/label.component.props.ts
  src/components/primitive/label/label.component.styles.ts
  src/components/primitive/label/label.component.tsx
Labels: enhancement

#115 #101 - Create Danger Zone component
  src/assets/icons/delete.svg
  src/assets/icons/edit.svg
  src/i18n/locales/en.json
  src/screens/safe-overview/components/danger-zone/danger-zone.component.styles.ts
  src/screens/safe-overview/components/danger-zone/danger-zone.component.tsx
  src/screens/safe-overview/components/guardian-list.component.tsx
  src/screens/safe-overview/safe-overview.screen.tsx
  src/themes/images.ts
Labels: enhancement, feature

#110 #78 - Create safe component
  package.json
  src/assets/icons/key.svg
  src/assets/icons/signature.svg
  src/components/primitive/create-safe/create-safe.component.props.ts
  src/components/primitive/create-safe/create-safe.component.tsx
  src/components/primitive/generic-modal/generic-modal.component.style.ts
  src/components/primitive/generic-modal/generic-modal.component.tsx
  src/i18n/locales/en.json
  src/themes/colors.ts
  src/themes/images.ts
  src/themes/palette.ts
  yarn.lock
Labels: enhancement

#116 #99 - Create safe fee component
  src/assets/icons/safe-fee.svg
  src/i18n/locales/en.json
  src/screens/safe-overview/components/guardian-list/guardian-list.component.tsx
  src/screens/safe-overview/components/index.ts
  src/screens/safe-overview/components/safe-fee/safe-fee.component.props.ts
  src/screens/safe-overview/components/safe-fee/safe-fee.component.tsx
  src/themes/images.ts
Labels: enhancement, feature

#121 #117 - Refactor Alert component and add Icon support. #117
  src/assets/icons/error-alert.svg
  src/assets/icons/info-alert.svg
  src/assets/icons/success-alert.svg
  src/assets/icons/warning-alert.svg
  src/components/primitive/alerts/alert.component.props.ts
  src/components/primitive/alerts/alert.component.styles.ts
  src/components/primitive/alerts/alert.component.tsx
  src/components/primitive/alerts/alert.component.utils.ts
  src/components/primitive/index.ts
  src/themes/colors.ts
  src/themes/images.ts
  src/themes/palette.ts
Labels: enhancement, feature
